# Programming Exercise 3: Multi-Class Classification

We'll be using the output from the previous exercise. Logistic Regression with regularizaton

In [1]:
# Importing the needed libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from logisticRegression import *
from multiClassClassification import *

# Optimization module in scipy
from scipy import optimize

# We'll use loadmap to load the matlab dataset
from scipy.io import loadmat

# tells matplotlib to embed plots within the notebook
%matplotlib inline

## Loading and parsing data from a Matlab file

In [2]:
data = loadmat('ex3data1.mat')
# This loads all the information on a dictonary
print(data)

{'__header__': b'MATLAB 5.0 MAT-file, Platform: GLNXA64, Created on: Sun Oct 16 13:09:09 2011', '__version__': '1.0', '__globals__': [], 'X': array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]]), 'y': array([[10],
       [10],
       [10],
       ...,
       [ 9],
       [ 9],
       [ 9]], dtype=uint8)}


In [3]:
# Looking at the dictionary keys
data.keys()

dict_keys(['__header__', '__version__', '__globals__', 'X', 'y'])

In [4]:
# We can access the contents of each dictionary key as an array
data['__header__']

b'MATLAB 5.0 MAT-file, Platform: GLNXA64, Created on: Sun Oct 16 13:09:09 2011'

In [5]:
# Having a look at the dataset
data['X'], data['y']

(array([[0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        ...,
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.]]),
 array([[10],
        [10],
        [10],
        ...,
        [ 9],
        [ 9],
        [ 9]], dtype=uint8))

In [6]:
# Convert the data into a numpy array
X = data['X']
y = data['y'].flatten()

y should be made of values from 0-9. However, as matlab does not have 0 index, the value is replaced by 10.
We'll normalize the 10 value back to 0, so it matches the 0 digit.

In [7]:
y = np.where(y == 10, 0, y)
# Another way to do it
# y[y == 10] = 0

In [8]:
y

array([0, 0, 0, ..., 9, 9, 9], dtype=uint8)

In [9]:
# m = number of training examples
# n = number of features
(m,n) = X.shape

## Visualizing the data

We'll visualize 100 random data points from the training set.

In [10]:
# We get a 100 random datapoints. First we get a 100 indices out of m
rand_indices = np.random.choice(m, 100, replace=False)
# Second, we load these random vectors in the sel array
sel = X[rand_indices, :]

## Vectorized logistic regression

In [11]:
# test values for the parameters theta
theta_t = np.array([-2, -1, 1, 2], dtype=float)

# test values for the inputs
X_t = np.concatenate([np.ones((5, 1)), np.arange(1, 16).reshape(5, 3, order='F')/10.0], axis=1)

# test values for the labels
y_t = np.array([1, 0, 1, 0, 1])

# test value for the regularization parameter
lambda_t = 3

In [12]:
J, grad = costFunction(theta_t, X_t, y_t, lambda_t)

print('Cost         : {:.6f}'.format(J))
print('Expected cost: 2.534819')
print('-----------------------')
print('Gradients:')
print(' [{:.6f}, {:.6f}, {:.6f}, {:.6f}]'.format(*grad))
print('Expected gradients:')
print(' [0.146561, -0.548558, 0.724722, 1.398003]');

Cost         : 2.534819
Expected cost: 2.534819
-----------------------
Gradients:
 [0.146561, -0.548558, 0.724722, 1.398003]
Expected gradients:
 [0.146561, -0.548558, 0.724722, 1.398003]


## One-vs-All Classification

In [13]:
lmbd = 0.1
num_labels = 10
all_theta, all_cost = oneVsAll(X, y, num_labels, lmbd)

In [14]:
pred = predictOneVsAll(all_theta, X)

In [15]:
print('\nTraining Set Accuracy: {:.2f} %'.format(np.mean(pred == y) * 100));


Training Set Accuracy: 96.46 %
